import type { Metadata } from 'next'
import './globals.css'



export const metadata: Metadata = {
  title: 'Trello 2.O clone',
  description: 'Generated by Mangi Lal',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
